<?php
/**
    Bitte honorieren Sie unsere Arbeit und beachten Sie unsere Nutzungsbedingungen.
    Kostenlose Nutzung mit Backlink: http://creativecommons.org/licenses/by/2.0/de/
    Kommerzielle Lizenz ohne Backlink wird ab Version 1.0 verfuegbar sein.
    
    Please take care of our terms of use.
    Free using with link back to us: http://creativecommons.org/licenses/by/2.0/de/deed.en_GB
    Commercial Licence will follow with version 1.0.
 */
?>
<div><?php echo $this->getChildHtml() ?></div>
<div class="copyright"><?php echo $this->getCopyright() ?></div>
<div class="copyright">Powered by <a href="http://www.techdivision.com">TechDivision GmbH</a></div>